[package]
name = "server"
version = "0.5.0"
authors = ["The async-rs developers", "quininer <quininer@live.com>"]
edition = "2018"

[dependencies]
structopt = "0.3.9"
async-std = "1.5.0"
async-tls = { path = "../.." }
rustls = "0.19.0"
webpki = "0.21.3"
